// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7jPDuMo_KEiFXTuTN8FWc07GOH8Ne7tY',
    appId: '1:960391654911:web:10cd5b28f9bcd4ecfa0bca',
    messagingSenderId: '960391654911',
    projectId: 'hotelonwer-2f95e',
    authDomain: 'hotelonwer-2f95e.firebaseapp.com',
    storageBucket: 'hotelonwer-2f95e.appspot.com',
    measurementId: 'G-BBBT5RMKQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDziSCImtcOXNtj9aLdrsY-SxjK-2mzlw',
    appId: '1:960391654911:android:3709ab7dc1b42f51fa0bca',
    messagingSenderId: '960391654911',
    projectId: 'hotelonwer-2f95e',
    storageBucket: 'hotelonwer-2f95e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE7OxdVTPtxoKjjcfOOZgn1ewT7zy_EW4',
    appId: '1:960391654911:ios:eff17114d68a8d25fa0bca',
    messagingSenderId: '960391654911',
    projectId: 'hotelonwer-2f95e',
    storageBucket: 'hotelonwer-2f95e.appspot.com',
    androidClientId: '960391654911-ua347dm6r30ljv37tdp3126rs4titfiq.apps.googleusercontent.com',
    iosClientId: '960391654911-5rububtqis0f44s1fusrmpr5qmog6gh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bedmyway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE7OxdVTPtxoKjjcfOOZgn1ewT7zy_EW4',
    appId: '1:960391654911:ios:eff17114d68a8d25fa0bca',
    messagingSenderId: '960391654911',
    projectId: 'hotelonwer-2f95e',
    storageBucket: 'hotelonwer-2f95e.appspot.com',
    androidClientId: '960391654911-ua347dm6r30ljv37tdp3126rs4titfiq.apps.googleusercontent.com',
    iosClientId: '960391654911-5rububtqis0f44s1fusrmpr5qmog6gh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bedmyway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7jPDuMo_KEiFXTuTN8FWc07GOH8Ne7tY',
    appId: '1:960391654911:web:a711acf261b1d692fa0bca',
    messagingSenderId: '960391654911',
    projectId: 'hotelonwer-2f95e',
    authDomain: 'hotelonwer-2f95e.firebaseapp.com',
    storageBucket: 'hotelonwer-2f95e.appspot.com',
    measurementId: 'G-JW51JJC8GP',
  );
}
